//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_CC_TT_LEE_NAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cham_Cong_Full_Time
    {
        public int id_Full_Time { get; set; }
        public string id_Nhan_Vien { get; set; }
        public Nullable<bool> Diem_Danh { get; set; }
        public Nullable<bool> Di_Muon { get; set; }
        public Nullable<System.DateTime> Ngay_Lam { get; set; }
        public Nullable<System.TimeSpan> Gio_Vao { get; set; }
        public Nullable<bool> Nghi_Phep { get; set; }
        public string Ly_Do { get; set; }
        public Nullable<bool> Tang_Ca { get; set; }
        public Nullable<System.TimeSpan> Gio_Bat_Dau { get; set; }
        public Nullable<System.TimeSpan> Gio_Ket_Thuc { get; set; }
    
        public virtual Cong_Viec Cong_Viec { get; set; }
    }
}
