//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_CC_TT_LEE_NAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cong_Viec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cong_Viec()
        {
            this.Cham_Cong_Full_Time = new HashSet<Cham_Cong_Full_Time>();
            this.Cham_Cong_Part_Time = new HashSet<Cham_Cong_Part_Time>();
        }
    
        public string id_Nhan_Vien { get; set; }
        public string Ten_Cong_Viec { get; set; }
        public string Loai_Cong_Viec { get; set; }
        public Nullable<double> He_So_Luong { get; set; }
        public string Mo_Ta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cham_Cong_Full_Time> Cham_Cong_Full_Time { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cham_Cong_Part_Time> Cham_Cong_Part_Time { get; set; }
        public virtual Nhan_Vien Nhan_Vien { get; set; }
    }
}
