//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_CC_TT_LEE_NAM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_CC_TTEntities : DbContext
    {
        public QL_CC_TTEntities()
            : base("name=QL_CC_TTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ca_Lam> Ca_Lam { get; set; }
        public virtual DbSet<Cham_Cong_Full_Time> Cham_Cong_Full_Time { get; set; }
        public virtual DbSet<Cham_Cong_Part_Time> Cham_Cong_Part_Time { get; set; }
        public virtual DbSet<Chuc_Vu> Chuc_Vu { get; set; }
        public virtual DbSet<Cong_Viec> Cong_Viec { get; set; }
        public virtual DbSet<Khen_Thuong> Khen_Thuong { get; set; }
        public virtual DbSet<Ky_Luat> Ky_Luat { get; set; }
        public virtual DbSet<Luong_Full> Luong_Full { get; set; }
        public virtual DbSet<Luong_Part> Luong_Part { get; set; }
        public virtual DbSet<Nguoi_Dung> Nguoi_Dung { get; set; }
        public virtual DbSet<Nhan_Vien> Nhan_Vien { get; set; }
        public virtual DbSet<Phong_Ban> Phong_Ban { get; set; }
        public virtual DbSet<Phu_Cap> Phu_Cap { get; set; }
    }
}
