//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_CC_TT_LEE_NAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khen_Thuong
    {
        public int id_Khen_Thuong { get; set; }
        public string id_Nhan_Vien { get; set; }
        public string Ly_Do_KT { get; set; }
        public Nullable<int> So_Tien { get; set; }
        public Nullable<System.DateTime> Ngay_Khen_Thuong { get; set; }
    
        public virtual Nhan_Vien Nhan_Vien { get; set; }
    }
}
