//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_CC_TT_LEE_NAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nguoi_Dung
    {
        public string id_Nhan_Vien { get; set; }
        public string Tai_Khoan { get; set; }
        public string Mat_Khau { get; set; }
        public string Phan_Quyen { get; set; }
        public string Gmail { get; set; }
    
        public virtual Nhan_Vien Nhan_Vien { get; set; }
    }
}
