//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_CC_TT_LEE_NAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhan_Vien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nhan_Vien()
        {
            this.Khen_Thuong = new HashSet<Khen_Thuong>();
            this.Ky_Luat = new HashSet<Ky_Luat>();
        }
    
        public string id_Nhan_Vien { get; set; }
        public string Ho_Ten { get; set; }
        public string Gioi_Tinh { get; set; }
        public Nullable<System.DateTime> Ngay_Sinh { get; set; }
        public string Que_Quan { get; set; }
        public string Dia_Chi { get; set; }
        public string Dan_Toc { get; set; }
        public string CCCD { get; set; }
        public string Gmail { get; set; }
        public string SDT { get; set; }
        public string Ton_Giao { get; set; }
        public string Trinh_Do { get; set; }
        public string Ngoai_Ngu { get; set; }
        public Nullable<int> Point { get; set; }
        public byte[] Hinh_Anh { get; set; }
        public string id_Phong_Ban { get; set; }
        public string id_Chuc_Vu { get; set; }
        public string id_Phu_Cap { get; set; }
    
        public virtual Chuc_Vu Chuc_Vu { get; set; }
        public virtual Cong_Viec Cong_Viec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Khen_Thuong> Khen_Thuong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ky_Luat> Ky_Luat { get; set; }
        public virtual Nguoi_Dung Nguoi_Dung { get; set; }
        public virtual Phong_Ban Phong_Ban { get; set; }
        public virtual Phu_Cap Phu_Cap { get; set; }
    }
}
