//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_CC_TT_LEE_NAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong_Ban
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong_Ban()
        {
            this.Luong_Full = new HashSet<Luong_Full>();
            this.Luong_Part = new HashSet<Luong_Part>();
            this.Nhan_Vien = new HashSet<Nhan_Vien>();
        }
    
        public string id_Phong_Ban { get; set; }
        public string Ten_Phong_Ban { get; set; }
        public string Dia_Chi { get; set; }
        public string Lien_He { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Luong_Full> Luong_Full { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Luong_Part> Luong_Part { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nhan_Vien> Nhan_Vien { get; set; }
    }
}
