//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_CC_TT_LEE_NAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phu_Cap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phu_Cap()
        {
            this.Nhan_Vien = new HashSet<Nhan_Vien>();
        }
    
        public string id_Phu_Cap { get; set; }
        public string Ten_Phu_Cap { get; set; }
        public Nullable<int> So_Tien { get; set; }
        public string Mo_Ta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nhan_Vien> Nhan_Vien { get; set; }
    }
}
